config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sections/', include("section.urls")),
]

section/urls.py
from django.conf.urls import url

from section.views import SectionsListView,SectionsAddView,SectionUpdateView

app_name = "sections"

urlpatterns = [
    url(r'^$',SectionsListView.as_view(),name='index'),
    url(r"^(?P<pk>\d+)/$", SectionUpdateView.as_view(), name="update"),
    url(r'^create/$',SectionsAddView.as_view(),name='create')
]

section/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models

# Create your models here.
class Section(models.Model):
    name = models.CharField(_("Section Name"), blank=True, max_length=255)
    duration = models.IntegerField(_("Duration"), blank=True, null=True)
    cut_off = models.PositiveSmallIntegerField(_("Cut Off"), default=0, blank=True)
    instructions = models.TextField(_("Instructions"), blank=True)
    max_num_of_questions_attemptable = models.PositiveSmallIntegerField(
        _("Maximum number of questions that can be attempted in the section"), blank=True, null=True
    )
    parent = models.ForeignKey("self", related_name="children", on_delete=models.CASCADE, null=True, blank=True)
    number_of_sections_to_attempt = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = _("Section")
        verbose_name_plural = _("Sections")

    def __str__(self):
        return self.name

section/forms.py
from django import forms
from section.models import Section
from extra_views import InlineFormSetFactory
from django.utils.translation import ugettext_lazy as _
from django.forms.models import BaseInlineFormSet


class SectionForm(forms.ModelForm):
    parent = forms.ModelChoiceField(label="parent", queryset=None, required=False)
    duration = forms.IntegerField(label="Duration in minutes", required=False,)
    error_messages = {
        "duplicate_section_name": _("A section with that name already exists."),
    }

    class Meta:
        model = Section
        fields = (
            "name",
            "duration",
            "cut_off",
            "instructions",
            "parent",
            "number_of_sections_to_attempt",
        )
    
    def clean_name(self):
        name = self.cleaned_data["name"]
        queryset = Section.objects.filter(name=name)
        if self.instance.pk:
            if queryset.exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError(
                    self.error_messages["duplicate_section_name"], code="duplicate_section_name"
                )
        elif Section.objects.filter(name=name).exists():
            raise forms.ValidationError(self.error_messages["duplicate_section_name"], code="duplicate_section_name")
        return name

class ChildSectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = (
            "name",
        )

class SectionInlineFormSet(BaseInlineFormSet):
    def clean(self):
        super(SectionInlineFormSet, self).clean()
        if any(self.errors):
            return

        values = []
        deletes = []
        for form in self.forms:
            value = form.cleaned_data.get("name", None)
            delete = form.cleaned_data.get("DELETE", None)

            if value and value in values:
                raise forms.ValidationError("Duplicate Sub Section are not allowed")

            if delete is not None:
                deletes.append(delete)

            if value and not delete:
                values.append(value)

class SectionInline(InlineFormSetFactory):
    model = Section
    form_class = ChildSectionForm
    formset_class = SectionInlineFormSet
    factory_kwargs = {"extra": 0, "fk_name": "parent"}

section/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView
from django.utils.translation import ugettext_lazy as _
from extra_views import CreateWithInlinesView, NamedFormsetsMixin,UpdateWithInlinesView

from section.forms import SectionForm,SectionInline
from section.models import Section
from django.urls import reverse_lazy

# Create your views here.

class SectionsListView(ListView):
    context_object_name = "sections"
    template_name = "sections/list.html"
    queryset = Section.objects.filter(parent__isnull=True)


class SectionsAddView(NamedFormsetsMixin, CreateWithInlinesView):
    model = Section
    form_class = SectionForm
    inlines = [SectionInline]
    inlines_names = ["child_sections"]
    template_name = "sections/form.html"
    success_message = _("Section added successfully.")
    success_url = reverse_lazy("sections:index")

class SectionUpdateView(NamedFormsetsMixin, UpdateWithInlinesView):
    model = Section
    form_class = SectionForm
    inlines = [SectionInline]
    inlines_names = ["child_sections"]
    template_name = "sections/form.html"
    success_message = _("Section Updated successfully.")
    success_url = reverse_lazy("sections:index")

templates/includes/list_dropdown.html
<div x-data="{ open: false }" @keydown.escape="open = false" @click.away="open = false"
    class="relative flex items-center justify-end">
    <button id="project-options-menu-0" aria-haspopup="true" :aria-expanded="open" type="button" @click="open = !open"
        class="inline-flex items-center justify-center w-7 h-7 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none group-hover:text-gray-500"
        aria-expanded="false">
        <span class="sr-only">Open options</span>
        <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round"
                d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z">
            </path>
        </svg>
    </button>
    <div x-show="open" x-description="Dropdown panel, show/hide based on dropdown state."
        x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95"
        x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75"
        x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95"
        class="absolute top-0 z-10 w-48 mx-3 mt-1 origin-top-right bg-white divide-y divide-gray-200 rounded-md shadow-lg right-7 ring-1 ring-black ring-opacity-5"
        role="menu" aria-orientation="vertical" aria-labelledby="project-options-menu-0" style="display: none;">
        <div class="py-1" role="none">

            <a href="{% url 'sections:update' pk=section.id %}"
                class="flex items-center px-4 py-2 text-sm text-gray-700 group hover:bg-gray-100 hover:text-gray-900"
                rle="menuitem">
                <svg class="w-5 h-5 mr-3 text-gray-400 group-hover:text-gray-500" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M11 5H6a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2v-5m-1.414-9.414a2 2 0 1 1 2.828 2.828L11.828 15H9v-2.828l8.586-8.586z">
                    </path>
                </svg>
                Edit
            </a>
            <a href="#"
                class="flex items-center px-4 py-2 text-sm text-gray-700 group hover:bg-gray-100 hover:text-gray-900"
                rle="menuitem">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3 text-gray-400 group-hover:text-gray-500"
                    fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16">
                    </path>
                </svg>
                Delete
            </a>
        </div>
    </div>
</div>

templates/sections/list.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <script defer src="https://unpkg.com/alpinejs@3.4.2/dist/cdn.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body class="h-screen">
    <header>
        <nav class="bg-white border-b border-gray-200" x-data="{ open: false }">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex justify-between h-16">
                    <div class="flex">
                        <div class="flex-shrink-0 flex items-center">
                            <div class="text-2xl text-gray-900 tracking-wide">Navbar Goes Here</div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="max-w-7xl mx-auto xl:px-8">
            <div class="lg:py-6">
                <div class="relative pl-4 pr-2 sm:px-0 pt-9">
                    <div class="flex items-start justify-between mt-2">
                        <div class="md:flex md:items-center md:justify-between grow">
                            <div class="flex items-baseline flex-1 min-w-0">
                                <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                                    Sections
                                </h2>
                            </div>
                            <div class="flex flex-shrink-0 gap-2 mt-4 md:mt-0 md:ml-4">
                                <a href="{% url 'sections:create' %}" type="button"
                                    class="inline-flex items-center px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md shadow-sm bg-emerald-600 hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2 -ml-1" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253">
                                        </path>
                                    </svg>
                                    Create Section
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mt-6">
                    <div class="py-8 px-4 sm:px-8 bg-white shadow xl:rounded space-y-8">
                        <div class="border border-gray-200 rounded-md sm:ml-0">
                            <ul class="divide-y divide-gray-200">
                                {% for section in sections %}
                                <li class="flex justify-between items-center pl-5 py-3 pr-3">
                                    <div>
                                        <div class="flex space-x-2 items-center">
                                            <a href="#" class="text-sm font-medium text-emerald-600 " aria-disabled="true">
                                                {{section.name}}
                                            </a>
                                        </div>
                                    </div>
                                    {% include "includes/list_dropdown.html" %}
                                </li>
                                {% empty %}
                                <li>Not available</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>